language: go
go:
  - "1.9"
before_install:
  - openssl aes-256-cbc -K $encrypted_73c0eb2351cf_key -iv $encrypted_73c0eb2351cf_iv -in travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - echo -e "Host 111.230.242.177\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
addons:
  ssh_known_hosts: 111.230.242.177

script: go test -v ./...
  
after_success:
  - ssh jks@111.230.242.177 'cd $GOPATH/src/github.com/hzxiao/ocss-srv && sudo chmod +x ./publish.sh && ./publish.sh'