[server]
port = ":8999"
secret = "ocss"

[db]
conn = "ocss.h:27017"
name = "ocss"

[data]
deptPath = "data/dept.json"
majorPath = "data/major.json"


[file]
location = "/home/jks/app/files"
webPath = "/home/jks/app/ocss-front"